import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/toaster";
import {Header} from "@/app/components/header";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "卖号平台",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div
            className="bg-gray-50 text-black/85 bg-[url('https://w.wallhaven.cc/full/we/wallhaven-werowr.png')] bg-fixed bg-cover min-h-screen">
            <Header/>
            {children}
        </div>
        <Toaster/>
        </body>
        </html>
    );
}
